steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/next-supabase-app', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'run'
    - 'deploy'
    - 'next-supabase-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/next-supabase-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
