version: '3'

services:
  web:
    image: time-app
    ports:
      - '3000:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
