version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./config:/app/config
    command: bash -c "npm install && npm run dev"
